import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { ReactNode } from "react";

import "./globals.css";
import { AccountProvider } from "@/providers/account-provider";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import type { AccountIdentity } from "@/components/account/identity/types";
import type { AccountProfile } from "@/lib/account-user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function buildDisplayName(
  fullName?: string | null,
  email?: string | null,
  fallback = "Account",
) {
  const trimmedFullName = fullName?.trim();
  if (trimmedFullName) return trimmedFullName;

  const emailPrefix = email?.split("@")[0]?.trim();
  if (emailPrefix) return emailPrefix;

  return fallback;
}

function buildInitialAccountIdentity(
  user: {
    id: string;
    email?: string | null;
    user_metadata?: Record<string, unknown> | null;
  },
  profile: AccountProfile | null,
): AccountIdentity {
  const metadata = (user.user_metadata ?? {}) as Record<string, unknown>;

  const fullName =
    (typeof profile?.full_name === "string" ? profile.full_name : null) ??
    (typeof metadata.full_name === "string" ? metadata.full_name : null) ??
    (typeof metadata.name === "string" ? metadata.name : null) ??
    null;

  return {
    id: user.id,
    name: buildDisplayName(fullName, profile?.email ?? user.email ?? null, "User"),
    email: profile?.email ?? user.email ?? "",
    image: profile?.avatar_url ?? null,
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const supabase = await createServerSupabaseClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  let initialUser: AccountIdentity | null = null;
  let initialProfile: AccountProfile | null = null;

  if (user) {
    const { data: profile } = await supabase
      .from("profiles")
      .select("id, email, full_name, first_name, last_name, avatar_url, completed, created_at, updated_at")
      .eq("id", user.id)
      .maybeSingle();

    if (profile) {
      initialProfile = {
        id: profile.id,
        email: profile.email,
        full_name: profile.full_name ?? null,
        first_name: profile.first_name ?? null,
        last_name: profile.last_name ?? null,
        avatar_url: profile.avatar_url ?? null,
        completed: profile.completed ?? false,
        created_at: profile.created_at ?? null,
        updated_at: profile.updated_at ?? null,
      };
    }

    initialUser = buildInitialAccountIdentity(user, initialProfile);
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AccountProvider
          initialUser={initialUser}
          initialProfile={initialProfile}
          initialLoading={false}
        >
          {children}
        </AccountProvider>
      </body>
    </html>
  );
}